### ISSUE TITLE
AppView 내용에 관해서.

### ISSUE THREAD

**Issue by starlightcandy** [Yoon-jae/team02_week4#14]
AppView에서 데이터 파일을 읽어들여 ClientAccountData에 넣어주어야 하는데, 이 경우에 값을 어떻게 넘겨줄 것인지, 클래스 구조에 대한 구체적인 의논이 필요함.
일단 현재는 읽어들인 값을 2차원 배열로 파싱되게 해 놓았음.
파일의 형태는 아래와 같음.

파일 형식 - input.txt
AccountID Hostname Plan EmailAddress LineNumbers
lineUsername phoneNumber usedMin
lineUsername phoneNumber usedMin
lineUsername phoneNumber usedMin
lineUsername phoneNumber usedMin

**Comment by Yoon-jae** [comment]
input.txt

PlanName(Gold/Silver)
NumberOfLine(n)
UserName UsedMinute
UserName UsedMinute
UserName UsedMinute
Jegal 200
Sang 300
Kim 405
